micronaut:
  application:
    name: mydb
  server:
    port: 8081

postgres:
  reactive:
    client:
      port: 5432
      host: localhost
      database: kanjava
      user: postgres
      password: kanjava
